### ISSUE TITLE
[Infra] 배포 프로세스 재정립

### ISSUE THREAD

**Issue by koreanddinghwan** [manito42/backend#42]
## Flow

1. develop merge
2. S3 Upload
3. trigger codebuild, 2번 버킷의 소스코드 사용.
    - codebuild는 vpc설정가능
    - 또한 subnet도 설정가능(즉, private subnet의 database와 연동가능)
4. code build완료까지 대기
5. code deploy 트리거

<br>

###  1. github action 예시

```yaml
name: AWS S3 Upload and CodeBuild

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload source code to S3
        run: |
          aws s3 cp . s3://your-source-code-bucket/ --recursive --exclude ".git/*" --exclude ".github/*"

      - name: Trigger CodeBuild
        run: |
          aws codebuild start-build --project-name YourCodeBuildProjectName --source-version ${{ github.sha }}

      - name: Wait for CodeBuild completion
        run: |
          # Poll AWS CodeBuild status until the build completes
          # You might need to implement this using AWS CLI or SDK in your preferred language

      - name: Deploy to AWS CodeDeploy
        run: |
          # Use AWS CLI or SDK to deploy to CodeDeploy
          # Update the commands to suit your deployment process
```

<br>

### buildspec.yml 예시

```yaml
version: 0.2

run-as: Linux-user-name

env:
  shell: shell-tag
  variables:
    key: "value"
    key: "value"
  parameter-store:
    key: "value"
    key: "value"
  exported-variables:
    - variable
    - variable
  secrets-manager:
    key: secret-id:json-key:version-stage:version-id
  git-credential-helper: no | yes

proxy:
  upload-artifacts: no | yes
  logs: no | yes

batch:
  fast-fail: false | true
  # build-list:
  # build-matrix:
  # build-graph:
        
phases:
  install:
    run-as: Linux-user-name
    on-failure: ABORT | CONTINUE
    runtime-versions:
      runtime: version
      runtime: version
    commands:
      - command
      - command
    finally:
      - command
      - command
    # steps:
  pre_build:
    run-as: Linux-user-name
    on-failure: ABORT | CONTINUE
    commands:
      - command
      - command
    finally:
      - command
      - command
    # steps:
  build:
    run-as: Linux-user-name
    on-failure: ABORT | CONTINUE
    commands:
      - command
      - command
    finally:
      - command
      - command
    # steps:
  post_build:
    run-as: Linux-user-name
    on-failure: ABORT | CONTINUE
    commands:
      - command
      - command
    finally:
      - command
      - command
    # steps:
reports:
  report-group-name-or-arn:
    files:
      - location
      - location
    base-directory: location
    discard-paths: no | yes
    file-format: report-format
artifacts:
  files:
    - location
    - location
  name: artifact-name
  discard-paths: no | yes
  base-directory: location
  exclude-paths: excluded paths
  enable-symlinks: no | yes
  s3-prefix: prefix
  secondary-artifacts:
    artifactIdentifier:
      files:
        - location
        - location
      name: secondary-artifact-name
      discard-paths: no | yes
      base-directory: location
    artifactIdentifier:
      files:
        - location
        - location
      discard-paths: no | yes
      base-directory: location
cache:
  paths:
    - path
    - path

```
